### ISSUE TITLE
Does the Gripper work?

### ISSUE THREAD

**Issue by Juphex** [pranshumalik14/intuitive-arm-reach#1]
Hey,

first of all: Amazing project! :) 
I did not see the gripper in the visualization moving. So it is not considered in this project, right?

**Comment by pranshumalik14** [comment]
Hi, thanks! Means a lot :) 

Yes, you're right in observing that. In our model we left the gripper as a non-movable object (see the urdf file). But since it only rotates on its axis with no positional change for the end effector, we chose to keep it that way to have lesser variables and quicker convergence in the optimization. But I don't see any problem with including a pose/orientation cost into the solver and including gripper as a movable limb. If you need it, probably it's best to start with adding changes to the Julia code (pdff_impl.jl Pluto notebook), coding a gripper to include pose (assuming 3D orientation but on a 2D plane for visualization), and if that works then porting it into the python files should be straightforward and doable. Let me know if you encounter any issues along the way.

Best of luck!
